spring.application.name=cv-analyzer
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.model=gpt-4o-mini

spring.datasource.url=jdbc:mysql://localhost:3306/cv_analyzer
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true